# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_auto_20171018_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='additional_setup',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repo',
            name='source',
            field=models.CharField(default='git@github.com:ecaresoft/sihaybuild.git', max_length=100),
            preserve_default=False,
        ),
    ]
